"""Emit the Samvaad console configuration for every agent tool.

The console wants each tool added by hand — name, description, cURL. Typing 21
of those invites drift between what the agent believes a tool does and what it
actually does, so this generates them straight from agent.TOOLS. Re-run it
after changing a tool and paste the result back into the console:

    python3 backend/samvaad_config.py > docs/samvaad-setup.md
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import agent  # noqa: E402

BASE = "https://chhotuai.vercel.app"

INSTRUCTIONS = """\
Tum "Chhotu" ho — ek hardware shop ka assistant. Dukaan ka maalik tumse Hindi,
English ya dono mila kar baat karega. Usi zubaan mein jawab do jismein usne
poochha, aur chhote jawab do — do line se zyada nahi, kyunki jawab bola jaata
hai, padha nahi jaata.

Sabse zaroori niyam: **koi bhi number khud mat banao.** Stock, rate, udhaar,
sale — har aankda tool se aayega. Agar tool ne kuch nahi diya, saaf keh do ki
pata nahi. Andaaza lagana galat jawab dene se bhi bura hai.

Har tool ka jawab do hisse mein aata hai: structured data aur ek chhota
`speak`. `speak` sirf ek fallback hai — tum data padh kar apne shabdon mein,
caller ki tarah baat karo.

Agar tool ke jawab mein `needs` aaye, matlab kuch saaf nahi hai. Aage mat
badho — wahi sawaal caller se poochho aur uske jawab ke baad tool dobara
chalao. Do cement ho to "kaunsa" poochhna sahi hai, apne aap chunna galat.

Kaam karne se pehle:
- Sale, purchase, payment ya stock badalne se pehle ek baar dohra kar confirm
  karo: "10 bori PPC, 420 rupaye — likh doon?"
- WhatsApp par kuch bhejne se pehle hamesha ijaazat lo.
- Udhaar bina customer ke naam ke kabhi mat likho.

Call shuru hote hi `shop_profile` chalao taaki dukaan ka context mil jaaye.
Aaj ki date bhi wahin se lo, apne se mat socho.
"""


def curl(tool: str) -> str:
    return (f"curl -X POST {BASE}/api/agent/tool \\\n"
            f"  -H 'Content-Type: application/json' \\\n"
            f"  -H 'X-Agent-Secret: <SAMVAAD_WEBHOOK_SECRET>' \\\n"
            f"  -d '{{\"tool\": \"{tool}\", \"caller\": \"{{{{caller_number}}}}\","
            f" \"shop_key\": \"{{{{shop_key}}}}\", \"args\": {{}}}}'")


def main() -> None:
    tools = agent.manifest()
    print("# Samvaad console setup\n")
    print("Generated by `backend/samvaad_config.py` — regenerate rather than "
          "editing by hand.\n")
    print("## Agent instructions\n")
    print("```\n" + INSTRUCTIONS + "```\n")
    print("## Variables\n")
    print("| Name | Where it comes from |")
    print("| --- | --- |")
    print("| `caller_number` | The calling number, for telephony sessions. |")
    print("| `shop_key` | `GET /api/voice/session` for the logged-in owner, "
          "for in-app sessions. |\n")
    print(f"## Tools ({len(tools)})\n")
    print("All of them POST to the same endpoint and differ only in `tool` and "
          "`args`. Every one runs **During conversation**, except "
          "`shop_profile`, which runs **On start**.\n")
    for t in tools:
        print(f"### `{t['name']}`\n")
        print(t["description"] + "\n")
        print("```bash\n" + curl(t["name"]) + "\n```\n")


if __name__ == "__main__":
    main()
